[[authentication]]
# Authentication
Stefan Wintermeyer <sw@wintermeyer-consulting.de>

There are several authentication libraries that you could use with your Phoenix
app, but instead of any of those, we are going to use
https://hexdocs.pm/phx_gen_auth/overview.html[phx_gen_auth] to generate the
authentication code into our app.

[[running-the-generator]]
## Running the Generator

Let's start by creating a new Phoenix app:

[source,bash]
----
$ mix phx.new auth_demo
----

Next, `cd auth_demo` into the new directory, check the database configuration is
correct and then create the database:

[source,bash]
----
$ mix ecto.create
----

We now need to edit the `mix.exs` file, adding the `phx_gen_auth` dependency:

.mix.exs
[source,elixir]
----
  defp deps do
    [
      ...
      {:phx_gen_auth, "~> 0.5", only: [:dev], runtime: false},
      ...
    ]
  end
----

Then, download the dependency:

[source,bash]
----
$ mix do deps.get, deps.compile
----

Now we are ready to run the generator:

[source,bash]
----
$ mix phx.gen.auth Accounts User users <1>
Compiling 14 files (.ex)
Generated auth_demo app
* creating priv/repo/migrations/20201006050217_create_users_auth_tables.exs
* creating lib/auth_demo/accounts/user_notifier.ex
[...]
----
<1> In addition to creating templates, views and controllers, this command also
creates a new `MyApp.Accounts` context and two database tables - `users` and
`user_tokens`.

After running the generator, we will need to re-fetch the dependencies and run
the migrations. Then, we can try out our Phoenix app with authentication.

[source,bash]
----
$ mix deps.get
$ mix ecto.migrate
$ mix test <1>
$ iex -S mix phx.server <2>
----
<1> Run the tests.
<2> Start the server.

[[adding-email-notifications]]
## Add Email Notifications

There is one thing that is currently missing in our app. The generated code does
not actually send SMSs or emails to users. We need to set that up ourselves.

There are two popular email libraries:
https://hexdocs.pm/bamboo/readme.html[bamboo] and
https://hexdocs.pm/swoosh/Swoosh.html[swoosh]. In this example, we are going to
use bamboo.

Add bamboo to our list of dependencies, by adding `{:bamboo, "~> 1.5"},` to the
`deps` function in `mix.exs`, and fetch it by running `mix deps.get`.

[[setup-bamboo]]
### Setup Bamboo

First, we need to create a `Mailer` module with the following code:

.lib/auth_demo/mailer.ex
[source,elixir]
----
defmodule AuthDemo.Mailer do
  use Bamboo.Mailer, otp_app: :auth_demo
end
----

and then update the development config:

.config/dev.exs
[source,elixir]
----
[...]
# Bamboo configuration
config :auth_demo, AuthDemo.Mailer, adapter: Bamboo.LocalAdapter
----

and the test config:

.config/test.exs
[source,elixir]
----
[...]
# Bamboo test configuration
config :auth_demo, AuthDemo.Mailer, adapter: Bamboo.TestAdapter
----

NOTE: You will want to use a different adapter in production. There are many
adapters available. See the bamboo documentation for details.

To complete the setup, we are going to add a development route which enables us
to view the emails that have been sent:

.lib/auth_demo_web/router.ex
[source,elixir]
----
[...]
  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
[...]
----

[[update-generated-code]]
### Update Generated Code

We now need to update the `lib/auth_demo/accounts/user_notifier.ex` file so that
it uses bamboo to send emails:

.lib/auth_demo/accounts/user_notifier.ex
[source,elixir]
----
defmodule AuthDemo.Accounts.UserNotifier do
  import Bamboo.Email
  alias AuthDemo.Mailer

  @from_email "support@example.com"

  defp deliver(to, body) do<1>
    email =
      new_email(
        to: to,
        from: @from_email,
        subject: "Message from example.com",
        text_body: body
      )
      |> Mailer.deliver_later()<2>

    {:ok, email}
  end
[...]
----
<1> We have updated the `deliver/2` function, which previously just logged a
message to the terminal, so that it sends an email using bamboo.
<2> By default, `deliver_later` sends the email right away in the background.
This behavior is configurable.

If we run `mix test` now, we will see several tests failing. To fix that, we
need to make one small change to `test/support/fixtures/accounts_fixtures.ex`.
In the `extract_user_token/1` function, replace `captured.body` with
`captured.text_body`:

.test/support/fixtures/accounts_fixtures.ex
[source,elixir]
----
[...]
  def extract_user_token(fun) do
    {:ok, captured} = fun.(&"[TOKEN]#{&1}[TOKEN]")
    [_, token, _] = String.split(captured.text_body, "[TOKEN]")
    token
  end
[...]
----

And that's it! Now all the tests will pass, and the emails will be properly
sent.
