= Phoenix Framework Beginner's Guide
Stefan Wintermeyer <sw@wintermeyer-consulting.de>
:Revision: 0
:icons: font
:numbered:
:website: https://www.wintermeyer-consulting.de/books/phoenix
:doctype: book

ifdef::env-github[]
//Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Entities
:adoc: AsciiDoc
:db: DocBook
:daps: DAPS

# Preface

https://www.phoenixframework.org[Phoenix]'s learning curve is steep. I am not
going to sugar coat this book with a "this is easy" start. Many new Phoenix
developers have never worked with https://elixir-lang.org[Elixir] and it being
often their first functional programming language doesn't help either.

I learn best from "Hello World!" like examples. I do not care about abstract
ideas or programming theories. Give me a good and clean example and I make sense
of it for me. If you like this kind of teaching you are reading the right book.
Otherwise it is not too late for returning it.

* **This book teaches by presenting bite size code examples.** I created those
  examples in a way that you can understand them by reading it's code. In
  addition I add callouts with explanations next to the important source code
  lines.
* **This book is a step by step guide. We start at zero.** As few
  chicken-egg-problems as possible. You are expected to understand the basics of
  programming and HTML but other than that you don't have to have any knowledge
  of Phoenix or Elixir.
* **I will not hesitate to oversimply stuff.** My aim is to get you productive
  in the quickest time possible. There are other resources to learn the details.
* The web-applications in this book are not intended to become eye candy. We will
  not waste time and energy to make stuff beautiful.

And we are not going to build one giant application in the course of the book.
We tackle small problems which make sense within their realm. 

IMPORTANT: If a specific chapter or section doesn't interest you: Go ahead and
skip it. You can come back later if needed.

The chapter <<elixir-introduction.adoc#elixir_introduction>> offers a jump start
for everybody who hasn't worked with Elixir before. You don't have to work
through all examples. But you should read it to get the basic ideas of the
language.

Stefan Wintermeyer

PS: Please do send me feedback about this book by e-mail to
sw@wintermeyer-consulting.de and follow me on Twitter
(https://twitter.com/wintermeyer[@wintermeyer]). To receive positive feedback
from a reader is a happy moment for any author!

## Finding Help

During or after reading this book there will come the time when you have a
problem or a question. Here is my advise for those times:

* https://stackoverflow.com
+
My favorate spot to find help. There is a good chance somebody already had the
same problem and it is answered on https://stackoverflow.com[stackoverflow.com]. 
If not you normally get surprisingly fast answers for new questions.

* https://www.google.com
+
`Phoenix` is not an easy to search for term. There are millions of
construction companies with Phoenix in their name which can help you build a
house but don't offer any programming help at all. You often want to
add either `Framework` or `Elixir` to your search queries.

* Send me an e-mail to sw@wintermeyer-consulting.de
+
Feel free to send me an email if everything else doesn't help. Please add the
used Elixir and Phoenix version and other information which helps (e.g.
database and operation system). If possible, create first a question on
https://stackoverflow.com[stackoverflow.com] and send me an email with the link 
to that question. By that I can answer it for you and for everybody else who 
has the same problem in the future.

=== Training and Consulting

I offer Phoenix Framework beginners training and consulting. Onside and remote.
Please send me an email to sw@wintermeyer-consulting.de for an offer.

