[[preface]]
= Preface
Stefan Wintermeyer <sw@wintermeyer-consulting.de>

Learning https://elixir-lang.org[Elixir], https://www.phoenixframework.org[Phoenix]
and https://ash-hq.org[Ash] is a steep climb. No sugar-coating. This book aims
to make that ascent less steep. It's a guide crafted for beginners.

* *This is a step-by-step guide.* While no prior knowledge is required, a basic
understanding of programming and HTML will be beneficial.
* *Expect bite-sized "Hello World!" code examples.* Crafted for
comprehension just by reading the code, with added notes for clarity. No abstract
programming theories.
* *Simplicity is key here.* My goal is to get you productive ASAP. For in-depth
exploration, there are other resources.
* *Not a beauty contest.* We're not investing much time in aesthetics. This is
not a CSS design book.

If a section doesn't resonate with you, skip it. You can circle back later
if needed. I recommend reading the book in order, but it's not required.

Stefan Wintermeyer

PS: Your feedback is very much appreciated. Please do email me at
sw@wintermeyer-consulting.de and follow me on Twitter
https://twitter.com/wintermeyer[@wintermeyer].

== Seeking more help?

* https://stackoverflow.com[StackOverflow]: A great place to ask https://stackoverflow.com/questions/tagged/elixir[Elixir], https://stackoverflow.com/questions/tagged/phoenix-framework[Phoenix] and https://stackoverflow.com/questions/tagged/ash-framework[Ash] questions.
* https://www.google.com[Google]: For Phoenix-related queries, add 'Phoenix
Framework', 'Elixir' or 'Ash Framework' to refine your search.
* Discord: https://discord.gg/elixir[Elixir], https://discord.gg/elixir[Phoenix] (#phoenix channel) and https://discord.gg/D7FNG2q[Ash] have very helpful communities.
* Email me at sw@wintermeyer-consulting.de: Please post your question on
StackOverflow first and include the link in your email.

[[training]]
== Elixir, Phoenix and Ash Training

I offer remote and on-site Elixir, Phoenix and Ash beginner's training in English
and German. Please contact me with background information (e.g. group size,
location and prefered date) at sw@wintermeyer-consulting.de to discuss details.
