[[preface]]
# Preface
Stefan Wintermeyer <sw@wintermeyer-consulting.de>

https://www.phoenixframework.org[Phoenix]'s learning curve is steep. I am not
going to sugar-coat this book with a "this is easy" start. Buckle up for an
interesting ride, especially if https://elixir-lang.org[Elixir] is your first
functional programming language.

I learn best from "Hello World!" examples. I do not care about abstract
ideas or programming theories. Give me a good and clean example, and I can make sense
of it. If you like this kind of teaching, you are reading the right book. Please
follow the code breadcrumbs I use to teach.

* **This book teaches by presenting bite-sized code examples. Think of them as
  breadcrumbs that'll lead you.** I've created these examples in a way that you
  can understand by reading the code. I have also added notes with explanations
  next to the vital source code lines.
* **This book is a step-by-step guide. We start at zero.** A few chicken and egg
  problems are inescapable, but I keep those to a minimum. You should understand
  the basics of programming and HTML. Other than that, you don't have to have
  any knowledge of Phoenix or Elixir.
* **I will not hesitate to oversimply stuff.** I aim to get you productive in
  the quickest time possible. There are other resources to learn the details
  (e.g. the magic of OTP).
* The web-applications in this book are not intended to become eye candy. We will
  not waste time and energy to make them look beautiful.

And we are not going to build one giant application in the course of the book.
We tackle small problems which make sense within their realm.

IMPORTANT: If a specific chapter or section doesn't interest you: Go ahead and
skip it. You can come back later if needed.

The chapter xref:elixir-introduction.adoc[Elixir Introduction]
offers a jump-start for everybody who hasn't worked with Elixir before. You
don't have to work through all the examples. But you should read it to get the basic
ideas of the language.

Stefan Wintermeyer

PS: Please do send me feedback about this book by email to
sw@wintermeyer-consulting.de and follow me on Twitter
(https://twitter.com/wintermeyer[@wintermeyer]). To receive positive feedback
from a reader is a happy moment for any author!

## Finding Help

During or after reading this book, there will come a time where you'll have a
problem or a question. Here is my advice for those times:

* https://stackoverflow.com
+
StackOverflow is my favourite spot to find help. There is a good chance somebody
has already had the same problems you're struggling with and has received
answers. If not, you usually get surprisingly fast answers for new questions.

* https://www.google.com
+
`Phoenix` is not an easy-to-search-for term. There are millions of
construction companies with Phoenix in their name. These links can help you build a
house, but they don't offer any programming help at all. You often want to
add either `Framework` or `Elixir` to your search queries.

* Send me an email to sw@wintermeyer-consulting.de
+
Feel free to send me an email if you can't find the help you need. Please let
me know your Elixir and Phoenix versions and other useful information (e.g.
database and operating system). If possible, first create a question on
https://stackoverflow.com[stackoverflow.com] and send me an email with the link
to that question. With that, I can answer it for you and other users.

[[remote-training]]
=== Remote Training

I offer a one and two-day remote Phoenix beginners training. During the
training, we'll work via remote pair programing
(https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-pack[Visual
Studio with the Live Share extension]). This is an excellent way to get up to
speed. No previous Elixir knowledge is needed. You just need basic programming and 
HTML knowledge. Please send me an email to sw@wintermeyer-consulting.de for further information.

Onsite training is possible too. But that depends on the local coronavirus travel restrictions.
