[[preface]]
= Preface
Stefan Wintermeyer <sw@wintermeyer-consulting.de>

Learning https://elixir-phoenix-ash.com/elixir/[Elixir],
https://elixir-phoenix-ash.com/phoenix/[Phoenix] and
https://elixir-phoenix-ash.com/ash/[Ash] is a
steep climb. No sugar-coating. This book aims to make that ascent
less steep. It's a guide crafted for beginners.

* *A step-by-step guide.* While no prior knowledge is required, a basic
understanding of programming and HTML will be beneficial.
* *Bite-sized "Hello World!" code examples.* Crafted for
comprehension just by reading the code, with added notes for clarity. No abstract
programming theories.
* *Simplicity is key.* My goal is to get you productive ASAP.
* *Not a beauty contest.* We're not investing much time in aesthetics. This is
not a CSS design book.

If a section doesn't resonate with you, skip it. You can circle back later
if needed. I recommend reading the book in order, but it's not required.

Stefan Wintermeyer

PS: Your feedback is very much appreciated. Please do email me at
sw@wintermeyer-consulting.de and follow me on Twitter
https://twitter.com/wintermeyer[@wintermeyer].

[[training]]
== Elixir, Phoenix and Ash Training

I offer remote and on-site Elixir, Phoenix and Ash beginner's training in English
and German. Please contact me with background information (e.g. group size,
location and prefered date) at sw@wintermeyer-consulting.de to discuss details.
