site:
  title: An Elixir, Phoenix and Ash Beginner's Guide
  url: https://elixir-phoenix-ash.com
  start_page: book:index.adoc
  keys:
    google_analytics: 'G-B4DB8GLK8G'
content:
  sources:
  - url: .
    edit_url: false
    branches: HEAD

ui:
  bundle:
    url: ./ui-bundle/build/ui-bundle.zip
    snapshot: true
  output_dir: antora-assets
runtime:
  fetch: true
