site:
  title: Phoenix
  url: https://elixir-phoenix-ash.com
  start_page: book::index.adoc
  keys:
    google_analytics: 'G-B4DB8GLK8G'
content:
  sources:
  - url: .
    edit_url: false
    branches: HEAD

ui:
  bundle:
    url: https://github.com/wintermeyer/wincon-antora-ui/releases/download/latest/ui-bundle.zip
    snapshot: true
  supplemental_files: ./ui-supplemental
  output_dir: antora-assets
runtime:
  fetch: true
