site:
  title: An Elixir, Phoenix and Ash Beginner's Guide
  url: https://wintermeyer-consulting.de/phoenix
  start_page: book:index.adoc
  keys:
    google_analytics: 'G-B4DB8GLK8G'
content:
  sources:
  - url: https://github.com/wintermeyer/elixir-phoenix-ash.git
    branches: main

ui:
  bundle:
    url: https://github.com/wintermeyer/wincon-antora-ui/releases/download/latest/ui-bundle.zip
    snapshot: true
  supplemental_files: ./ui-supplemental
  output_dir: antora-assets
runtime:
  fetch: true
