site:
  title: Elixir
  url: https://wintermeyer-consulting.de/elixir
  start_page: book::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: elixir-book
ui:
  bundle:
    url: https://github.com/wintermeyer/wincon-antora-ui/releases/download/latest/ui-bundle.zip
    snapshot: true
  supplemental_files: ./elixir-book/ui-supplemental
  output_dir: antora-assets
output:
  dir: build/elixir-site
runtime:
  fetch: true
