[[bitwise-operators]]
=== Bitwise Operators
indexterm:[Elixir,Operators,Bitwise]

Bitwise operators in Elixir are low-level operators that manipulate the binary representation of integers. They can be useful in certain domains like computer graphics, cryptography, and network programming. Elixir provides the following bitwise operators:

* Bitwise AND (`band/2`): The `band/2` function returns a number that is the bitwise AND of the input numbers. In the resulting number, a bit is set if the corresponding bit is set in both input numbers.

[source,elixir]
----
iex> Bitwise.band(6, 3)
2
----

* Bitwise OR (`bor/2`): The `bor/2` function returns a number that is the bitwise OR of the input numbers. In the resulting number, a bit is set if the corresponding bit is set in either or both input numbers.

[source,elixir]
----
iex> Bitwise.bor(6, 3)
7
----

* Bitwise XOR (`bxor/2`): The `bxor/2` function returns a number that is the bitwise XOR of the input numbers. In the resulting number, a bit is set if the corresponding bit is set in exactly one of the input numbers (but not both).

[source,elixir]
----
iex> Bitwise.bxor(6, 3)
5
----

* Bitwise NOT (`bnot/1`): The `bnot/1` function returns a number that is the bitwise NOT of the input number. In the resulting number, a bit is set if the corresponding bit is not set in the input number.

[source,elixir]
----
iex> Bitwise.bnot(6)
-7
----

* Bitwise shift-left (`bsl/2`) and shift-right (`bsr/2`): The `bsl/2` function shifts the bits of the input number to the left, adding zeros to the right. The `bsr/2` function shifts the bits of the input number to the right, adding zeros to the left.

[source,elixir]
----
iex> Bitwise.bsl(6, 2)
24

iex> Bitwise.bsr(6, 2)
1
----

NOTE: I have never used these operators. They require a deeper understanding of the binary number system to use effectively.