[[ash]]
= Ash Framework
Stefan Wintermeyer <sw@wintermeyer-consulting.de>

link:https://ash-hq.org[ash-hq.org] says
*"Model your domain, derive the rest"* and that
makes sense once you understand the basics of the Ash Framework. But it
does not help you a lot in the beginning to grasp what it is.

May I ask you for a rain check about the Ash elevator pich?
I have to think more about it. Thank you!

Like the Phoenix Framework the Ash Framework has no shortage of
written documentation. But most of it is not beginner friendly
and very often a mystery in itself. This book and the
link:https://www.youtube.com/@elixir-phoenix-ash[@elixir-phoenix-ash YouTube channel]
is my attempt to fill this gap.

Please do not hesitate to contact me by email at
sw@wintermeyer-consulting.de if you have any questions or feedback.
And please do contact me in case you need onsite or remote training.

TIP: The official support channel of the Ash Framework community
can be found at https://elixirforum.com

include::minimal-ash-2x-setup-guide.adoc[]
include::resources/index.adoc[]
include::validations.adoc[]
include::relationships/index.adoc[]
