[[ash-attributes-validations]]
## Attributes Validations

Validations are used when xref:ash-constraints[constraints] are not
powerful enough.

Let me show you how to use validations with an online shop `product`
example.

include::../setup-fresh-app.adoc[]

Please create the following files:

[source,elixir,title='lib/app/shop/product.ex']
----
defmodule App.Shop.Product do
  use Ash.Resource,
    data_layer: Ash.DataLayer.Ets,
    domain: App.Shop,
    otp_app: :app

  attributes do
    uuid_primary_key :id

    attribute :name, :string do
      allow_nil? false
      public? true
    end

    attribute :price, :decimal do
      allow_nil? false
      public? true
    end

    attribute :use_by_date, :date do
      allow_nil? false
      public? true
    end
  end

  actions do
    default_accept [:name, :price, :use_by_date]
    defaults [:create, :read, :update, :destroy]
  end
end
----

[source,elixir,title='lib/app/shop.ex']
----
defmodule App.Shop do
  use Ash.Domain, otp_app: :app

  resources do
    resource App.Shop.Product do
      define :create_product, action: :create
      define :list_products, action: :read
      define :get_product_by_id, action: :read, get_by: :id
      define :get_product_by_name, action: :read, get_by: :name
      define :update_product, action: :update
      define :destroy_product, action: :destroy
    end
  end
end
----

### Custom Validations

We only add products to our shop that are not expired. For that we add
a custom validation for the `use_by_date` attribute. It must not be in
the past. We need to write a custom validation for that.

[source,elixir,title='lib/app/validations/in_the_future_or_today.ex']
----
defmodule App.Validations.InTheFutureOrToday do
  use Ash.Resource.Validation

  def validate(changeset, opts, _context) do
    case Ash.Changeset.fetch_argument_or_change(changeset, opts[:field]) do
      :error ->
        # in this case, they aren't changing the field
        :ok

      {:ok, value} ->
        case Date.compare(Date.utc_today(), value) do
          :gt ->
            {:error, field: opts[:field], message: "must be in the future or today"}

          _ ->
            :ok
        end
    end
  end
end
----

NOTE: Ash 3.x passes a third `context` argument (a
`Ash.Resource.Validation.Context`) to the `validate/3` callback. Old
Ash 2.x tutorials show a two-argument version; adjust accordingly if
you port code from there.

That validation can be used like this:

[source,elixir,title='lib/app/shop/product.ex']
----
defmodule App.Shop.Product do
  use Ash.Resource,
    data_layer: Ash.DataLayer.Ets,
    domain: App.Shop,
    otp_app: :app

  attributes do
    uuid_primary_key :id

    attribute :name, :string do
      allow_nil? false
      public? true
    end

    attribute :price, :decimal do
      allow_nil? false
      public? true
    end

    attribute :use_by_date, :date do
      allow_nil? false
      public? true
    end
  end

  validations do
    validate {App.Validations.InTheFutureOrToday, field: :use_by_date} <1>
  end

  actions do
    default_accept [:name, :price, :use_by_date]
    defaults [:create, :read, :update, :destroy]
  end
end
----
<1> Here we are using the validation `App.Validations.InTheFutureOrToday`.

Let's try it out:

```elixir
$ iex -S mix
iex(1)> App.Shop.create_product!(%{
                                   name: "Apple",
                                   price: Decimal.new("0.1"),
                                   use_by_date: ~D[2008-11-10]
                                 })
** (Ash.Error.Invalid) Invalid Error

* Invalid value provided for use_by_date: must be in the future or today.

Value: nil

    (ash 3.24.3) lib/ash/code_interface.ex:...: Ash.CodeInterface.create_act!/4
```

With custom validations you can solve pretty much any validation problem.
