[[ash-resource]]
## Resource
indexterm:[Ash, Resource]

Ash resources are used to model data and define actions which are used
to manipulate that data. In the Ash world we often compare the resources
with nouns and the actions with verbs.

In Ash 3.0, resources are grouped into domains - context boundaries where related resources
are defined together. This helps organize your application and makes it easier to understand
the relationships between resources.

[[ash-resource-to_do_list_example]]
### To-Do-List Example

To dive into resources we use a simple to-do-list application as an
example. As a preparation for this, use Igniter to create a new application:

```bash
$ mix archive.install hex igniter_new
$ mix igniter.new app --install ash
$ cd app
```

Alternatively, you can follow the xref:ash/ash-setup-guide.adoc[Ash Setup Guide] for other setup options.

We want to create a `task` resource which has a `content` attribute
and an `id` attribute as a primary key. We also want to include the
actions `create`, `read`, `update` and `delete`. Ash provides those
actions for free but we have to include them into the resource.

IMPORTANT: In Ash 3.0, resources need to be registered to a domain. The domain acts
as a boundary for related resources and provides a place to define shared functionality.
Each domain is registered with your application's OTP app.


### Configure the Domain

First, we need to configure our OTP app to recognize our domain:

[source,elixir,title='config/config.exs']
----
import Config

config :app, :ash_domains, [App.ToDoList]
----

Now we create the `ToDoList` domain module which contains the
resource `Task`.

[source,elixir,title='lib/app/to_do_list.ex']
----
defmodule App.ToDoList do
  use Ash.Domain, otp_app: :app

  resources do
    resource App.ToDoList.Task
  end
end
----

For the resource(s) we create a new directory:

```bash
$ mkdir -p lib/app/to_do_list
```

### Configure the Resource

The resource defines `attributes` which are the fields of the resource.
In our case we have two attributes: `id` and `content`. The `id` attribute
is a special attribute because it is the primary key of the resource. We
use the `uuid_primary_key` macro to define the `id` attribute as a primary
key. The `content` attribute is a simple string.

[source,elixir,title='lib/app/to_do_list/task.ex']
----
defmodule App.ToDoList.Task do
  use Ash.Resource, 
    data_layer: Ash.DataLayer.Ets, 
    domain: App.ToDoList,
    otp_app: :app

  attributes do
    uuid_primary_key :id
    attribute :content, :string
  end
end
----

In this example we use the
link:https://hexdocs.pm/ash/Ash.DataLayer.Ets.html[Ash.DataLayer.Ets] as
a database layer. ETS (Erlang Term Storage) is an in-memory data store
which is built into your Erlang system. For our training purpose this
is ideal because we don't have to install and configure a database.

IMPORTANT: ETS does not save any data to disk! With every restart of `iex` 
you have to re-create the example data. For production applications, 
you should use AshPostgres or another persistent data layer.

The resulting directory structure should look like this:

```bash
$ tree lib
lib
├── app
│   ├── application.ex
│   ├── to_do_list
│   │   └── task.ex
│   └── to_do_list.ex
└── app.ex

3 directories, 4 files
```

We now have a resource but because we haven't defined any actions we
can't do anything with it yet. Let's change that.

include::create.adoc[]
include::read.adoc[]
include::update.adoc[]
include::destroy.adoc[]

include::defaults.adoc[]
