[[ash-resource]]
## Resource
indexterm:[Ash, Resource]

Ash resources are used to model data and define actions which are used
to manipulate that data. In the Ash world we often compare the resources
with nouns and the actions with verbs.

[[ash-resource-to_do_list_example]]
### To-Do-List Example

To dive into resources we use a simple to-do-list application as an
example. As a preperation for this please use the
xref:ash/minimal-ash-2x-setup-guide.adoc[Minimal Ash 2.x Setup Guide] to
generate a new Elixir application.

We want to create a `task` resource which has a `content` attribute
and an `id` attribute as a primary key. We also want to include the
actions `create`, `read`, `update` and `delete`. Ash provides those
actions for free but we have to include them into the resource.

IMPORTANT: In the Ash world a resource needs to be registered to an
interal API. Please don't think of this as an external WebAPI. Ash
uses the term API for an internal programming interface. We call
our API `ToDoList`.

[TIP]
====
Do you like video tutorials? Have a look at the 3 minute video
"Ash Resource - Create, Read, Update and Destroy" in our
https://www.youtube.com/@elixir-phoenix-ash[@elixir-phoenix-ash YouTube Channel].


video::tYCL0Rk12no[youtube,width=640,height=360]
====

### Configure the internal API

We have to add an internal API a `config.exs` file.

[source,elixir,title='config/config.exs']
----
import Config

config :app, :ash_apis, [App.ToDoList]
----

Now we create the `ToDoList` API module which contains the
resource `Task`.

[source,elixir,title='lib/app/to_do_list.ex']
----
defmodule App.ToDoList do
  use Ash.Api

  resources do
    resource App.ToDoList.Task
  end
end
----

For the resource(s) we create a new directory:

```bash
$ mkdir -p lib/app/to_do_list/resources
```

### Configure the Resource

The resource defines `attributes` which are the fields of the resource.
In our case we have two attributes: `id` and `content`. The `id` attribute
is a special attribute because it is the primary key of the resource. We
use the `uuid_primary_key` macro to define the `id` attribute as a primary
key. The `content` attribute is a simple string.

[source,elixir,title='lib/app/to_do_list/resources/task.ex']
----
defmodule App.ToDoList.Task do
  use Ash.Resource, data_layer: Ash.DataLayer.Ets <1>

  attributes do
    uuid_primary_key :id
    attribute :content, :string
  end
end
----

<1> In this example we use the
link:https://hexdocs.pm/ash/Ash.DataLayer.Ets.html[Ash.DataLayer.Ets] as
a database layer. ETS (Erlang Term Storage) is an in memory data store
which is build into your Erlang system. For our training purpose this
is ideal because we don't have to install and configure a database (e.g.
PostgreSQL). **But ETS does not save any data to disk!** With every
restart of `iex` you have to re-create the example data.

The resulting directory structure should look like this:

```bash
$ tree lib
lib
├── app
│   ├── application.ex
│   ├── to_do_list
│   │   └── resources
│   │       └── task.ex
│   └── to_do_list.ex
└── app.ex

4 directories, 4 files
```

We now have a resource but because we haven't defined any actions we
can't do anything with it yet. Let's change that.

include::create.adoc[]
include::read.adoc[]
include::update.adoc[]
include::destroy.adoc[]

include::defaults.adoc[]
