## Preface

[Phoenix](https://www.phoenixframework.org)'s learning curve is steep. Very
steep! Most new Phoenix developers have never worked with
[Elixir](https://elixir-lang.org) and it being often their first functional
programming language doesn't help either. I am not going to sugar coat it with a
"this is easy" start. I hate those "this is easy" how-tos and tutorials which
provide by a way too complicated example of how to build something you have no
intention to build anyway. Mostly leaving a couple of steps out because the
author thought of them as obvious.

I learn best from Hello World like examples. I do not care about abstract ideas
or therories in the background. Give me a simple example and I can make sense of
it and if I can't the language is not for me.

* **This book teaches by presenting bite size code examples.** I created those
  examples in a way that one can understand them by reading it's code. I add
  additional information with callouts next to the source code lines.
* **This book is a step by step guide. We start at zero.** Step by step. As few
  chicken-egg-problems as possible. You are expected to understand the basics of
  programming and HTML but other than that you don't have to have any knowledge
  of Phoenix or Elixir.
* **I will not hesitate to oversimply stuff.** My aim is to get you productive
  in the quickest time possible. There are other resources to learn the details.
* The web-applications in this book are not intended to become eye candy. We will
  not waste time and energy to make stuff beautiful.

And we are not going to build one giant application in the course of the book.
We tackle small problems which make sense within their realm. If a specific
chapter doesn't interest you: Go ahead and skip it. You can come back later 
if needed.

The chapter <<elixir_introduction>> is special. Because if you have never worked 
with Elixir you want to read it. You don't have to work through all examples. 
But you have to read it to get the basic ideas of the language.

Stefan Wintermeyer

PS: Please do send me feedback (good and bad) by e-mail
(sw@wintermeyer-consulting.de) and follow me on Twitter
([@wintermeyer](https://twitter.com/wintermeyer)). To receive positive feedback
from a reader is a happy moment for any author!

### Finding Help

During or after reading this book there will come the time when you have a
problem or a question. Here is my advise for those times:

* https://www.google.com
+
`Phoenix` is not an easy to search for term. There are millions of
construction companies with Phoenix in their name which can help you build a
house but don't offer any programming help at all. You often want to
add either `Framework` or `Elixir` to your search queries.

* https://stackoverflow.com
+
My favorate spot to find help. There is a good chance somebody already had the
same problem and it is answered on stackoverflow.com. If not you normally get
surprisingly fast answers for new questions.

* Send me an e-mail to sw@wintermeyer-consulting.de
+
Feel free to send me an email if everything else doesn't help. Please add the
used Elixir and Phoenix version and other information which helps (e.g.
database and operation system). If possible, create first a question on
stackoverflow.com and send me an email with the link of that question. By that
I can answer it for you and for everybody else who has the same problem in the
future.

=== Training and Consulting

I offer Phoenix Framework beginners training and consulting. Onside and remote.
Please send me an email to sw@wintermeyer-consulting.de for an offer.
