== Preface

[Phoenix](https://www.phoenixframework.org) is very good but the initial
learning curve is steep. Very steep! Most new Phoenix developers have never
worked with [Elixir](https://elixir-lang.org) and it being their first
functional programming language doesn't help either. As with so many other
frameworks the usual how-tos and tutorials all start with "this is easy"
followed by a way too complicated example of how to build something you have no
intention to build anyway. Mostly leaving a couple of steps out because the
author thought of them as obvious.

* This book is written as a step by step guide. We start at zero. You are
  expected to understand the basics of programming and HTML but other than that
  you don't have to have any knowledge of Phoenix or Elixir.
* **I will not hesitate to oversimply stuff.** My aim is to get you productive
  in the quickest time possible. There are other good books to learn Elixir
  or OTP in detail once you are hooked.
* The applications in this book are not intended to become eye candy. We will
  not waste time and energy to make stuff beautiful.

And we are not going to build one giant application in the course of the book.
We tackle small problems which make sense within their realm. If a specific
chapter doesn't interest you: Go ahead and skip it. Only one expection: If you
have never worked with Elixir you have to start with <<elixir_introduction>>.

Stefan Wintermeyer

=== Finding Help

During or after reading this book there will come the time when you have a
problem or a question. Here is my advise for those times:

- https://www.google.com  
  `Phoenix` is not an easy to search for term. There are millions of
  construction companies with Phoenix in their name which can help you build a
  house but don't offer any programming help on their webpage. You often want to
  add either `Framework` or `Elixir` to your search queries.
- https://stackoverflow.com  
  My favorate spot to find help. There is a good chance somebody already had the
  same problem and it is answered on stackoverflow. If not you normally get
  surprisingly fast answers there for new questions.
- Send me an e-mail to sw@wintermeyer-consulting.de  
  Feel free to send me an email if everything else doesn't help. Please add the
  used Elixir and Phoenix version and other information which helps (e.g.
  database and operation system). If possible, create a first a question on
  stackoverflow.com and send me an email with the link of that question. By that
  I can answer it for you and for everybody who has the same problem in the
  future.

=== Training and Consulting

I offer Phoenix Framework beginners training and consulting. Onside and remote.
Please send me an email to sw@wintermeyer-consulting.de and give me some
background information (e.g. 1:1 training or a big group of attendees). I'll
send you an offer.
