[[ash-relationships]]
## Relationships
indexterm:[Ash, Relationships]

Relationships define connections between resources. In any application this
is the bread and butter of the data modeling.

In Ash 3.0, relationships are defined within resources that are part of a domain.
This allows Ash to effectively manage and navigate the connections between your data.

[[ash-relationships-setup]]
### Setup

We discuss relationships in the context of a simple online shop. To get started, create a new application using Igniter:

```bash
$ mix archive.install hex igniter_new
$ mix igniter.new app --install ash
$ cd app
```

Alternatively, you can follow the xref:ash/ash-setup-guide.adoc[Ash Setup Guide] for other setup options.

After setting up your application, create the following files for a `Product` resource:

[source,elixir,title='config/config.exs']
----
import Config

config :app, :ash_domains, [App.Shop]
----

[source,elixir,title='lib/app/shop.ex']
----
defmodule App.Shop do
  use Ash.Domain, otp_app: :app

  resources do
    resource App.Shop.Product
  end
end
----

[source,elixir,title='lib/app/shop/product.ex']
----
defmodule App.Shop.Product do
  use Ash.Resource, 
    data_layer: Ash.DataLayer.Ets,
    domain: App.Shop,
    otp_app: :app

  attributes do
    uuid_primary_key :id
    attribute :name, :string
    attribute :price, :decimal
  end

  actions do
    defaults [:create, :read, :update, :destroy]
  end
end
----

Now let's add code interface definitions in our domain to make working with the resource easier:

[source,elixir,title='lib/app/shop.ex']
----
defmodule App.Shop do
  use Ash.Domain, otp_app: :app

  resources do
    resource App.Shop.Product do
      define :create_product, action: :create
      define :read_products, action: :read
      define :get_product_by_id, action: :read, get_by: :id
      define :get_product_by_name, action: :read, get_by: :name
      define :update_product, action: :update
      define :destroy_product, action: :destroy
    end
  end
end
----

include::belongs_to.adoc[]
include::has_many.adoc[]
include::many_to_many.adoc[]
include::has_one.adoc[]
